In [64]:
from ray import tune
from ray.rllib.models import ModelCatalog
from ray.rllib.models.torch.torch_modelv2 import TorchModelV2
from ray.tune.registry import register_env
from ray.rllib.env.wrappers.pettingzoo_env import ParallelPettingZooEnv
from pettingzoo.mpe import simple_v2, simple_reference_v2, simple_reference_v3
import supersuit as ss
import torch
from torch import nn

import supersuit as ss

In [2]:
env = simple_reference_v2.parallel_env(max_cycles=25, continuous_actions=False)
# env = ss.pad_observations_v0(env)
env = ss.pettingzoo_env_to_vec_env_v1(env)

/home/tgdivy/Desktop/needing_to_communicate/petting_zoo_mpe/pettingzoo/utils/wrappers/base.py:66: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.
  warnings.warn(
/home/tgdivy/Desktop/needing_to_communicate/petting_zoo_mpe/pettingzoo/utils/wrappers/base.py:51: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.
  warnings.warn(


In [3]:
env.reset()
game = ss.stable_baselines3_vec_env_v0(env, num_envs, multiprocessing=False)
obs = game.reset()

NameError: name 'num_envs' is not defined

In [94]:
num_envs = 3
env = simple_reference_v2.parallel_env(max_cycles=25, continuous_actions=False)
# env = simple_reference_v2.env(max_cycles=25, continuous_actions=False)
# env = ss.pad_observations_v0(env)
env = ss.pettingzoo_env_to_vec_env_v1(env)

game = ss.concat_vec_envs_v1(env, num_envs, 1)
game.seed(1)
# game = ss.vectorize_aec_env_v0(env, num_envs, num_cpus=num_envs)
game.num_envs

/home/tgdivy/Desktop/needing_to_communicate/petting_zoo_mpe/pettingzoo/utils/wrappers/base.py:66: UserWarning: The `action_spaces` dictionary is deprecated. Use the `action_space` function instead.
  warnings.warn(
/home/tgdivy/Desktop/needing_to_communicate/petting_zoo_mpe/pettingzoo/utils/wrappers/base.py:51: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.
  warnings.warn(


6

In [99]:
obs = game.reset()
# game.step(([[0,0,0]]))
game.seed()

TypeError: seed() takes from 1 to 2 positional arguments but 3 were given

In [102]:
obs[0], obs[1]

(array([ 0.0000000e+00,  0.0000000e+00,  7.5000000e-01,  2.5000000e-01,
         2.5000000e-01,  2.5000000e-01,  7.5000000e-01,  2.5000000e-01,
         2.5000000e-01,  2.5000000e-01,  7.5000000e-01, -9.2534435e-01,
        -2.4318388e-01,  1.3500999e-03,  9.9485099e-01, -1.0974395e-01,
         1.4217862e+00,  2.5000000e-01,  7.5000000e-01,  2.5000000e-01,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00], dtype=float32),
 array([ 0.        ,  0.        ,  0.75      ,  0.25      ,  0.25      ,
         0.25      ,  0.75      ,  0.25      ,  0.25      ,  0.25      ,
         0.75      , -0.27009377, -1.4059908 ,  0.65660065, -0.16795598,
         0.5455066 ,  0.2589792 ,  0.75      ,  0.25      ,  0.25      ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],


In [103]:
obs[2], obs[3]

(array([ 0.        ,  0.        ,  0.75      ,  0.25      ,  0.25      ,
         0.25      ,  0.75      ,  0.25      ,  0.25      ,  0.25      ,
         0.75      , -0.31752744, -0.6881064 , -1.3845125 , -0.9942483 ,
        -1.3337282 , -0.5535475 ,  0.25      ,  0.75      ,  0.25      ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       dtype=float32),
 array([ 0.        ,  0.        ,  0.75      ,  0.25      ,  0.25      ,
         0.25      ,  0.75      ,  0.25      ,  0.25      ,  0.25      ,
         0.75      , -0.7359202 ,  0.6998107 , -1.8029053 ,  0.39366877,
        -1.7521209 ,  0.8343696 ,  0.25      ,  0.75      ,  0.25      ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       dtype=float32))

In [74]:
import numpy as np
action = np.zeros((6), dtype=int)+1
print(action)
obs = game.step(action)
game.render()

[1 1 1 1 1 1]


In [76]:
obs[1]

array([-1.3477217, -1.386628 , -1.3477217, -1.386628 , -1.3477217,
       -1.386628 ], dtype=float32)